#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Display information about subdomains.

get_record_info() {
  local domain="$1"
  local subdomain="$2"

  local record_type=$(nslookup "$subdomain.$domain" | awk '/^Type:/ {print $2}')
  local destination=$(nslookup "$subdomain.$domain" | awk '/^Address:/ {print $2}')

  echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

domain="$1"
subdomain="$2"

if [[ -z "$subdomain" ]]; then
  # Display information for default subdomains
  get_record_info "$domain" "www"
  get_record_info "$domain" "lb-01"
  get_record_info "$domain" "web-01"
  get_record_info "$domain" "web-02"
else
  # Display information for the specified subdomain
  get_record_info "$domain" "$subdomain"
fi
