#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Display information about subdomains.

domain="$1"
subdomain="$2"

get_record_info() {
    local record_type=$(dig +short "$1" "$2" | awk '{print $4}')
    local destination=$(dig +short "$1" "$2" | awk '{print $5}')
    echo "The subdomain $2 is a $record_type record and points to $destination"
}

get_record_info "$domain" "www"
get_record_info "$domain" "lb-01"
get_record_info "$domain" "web-01"
get_record_info "$domain" "web-02"

if [ -n "$subdomain" ]; then
    get_record_info "$domain" "$subdomain"
fi
