#!/bin/bash

# Update packages
apt-get update

# Install Nginx
apt-get install -y nginx

# Configure Nginx to listen on port 80
echo "Hello World!" | sudo tee /var/www/html/index.html

# Restart Nginx
service nginx restart > /dev/null
