#!/usr/bin/env bash
# script that uses ssh to connect to your server with
# server ubuntu using the private key

# server -01 login


eval $("ssh-agent")

ssh-add ~/.ssh/school


ssh ubuntu@52.204.165.231
